# Stage 1: Build
FROM maven:3.9.2-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2: Run
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar 
# El .jar compilado se copia y se renombra como app.jar en el contenedor. Esto simplifica el ENTRYPOINT porque siempre sabes cómo se llama el archivo a ejecutar.
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]
